<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\EmployeeSeniorityHourRecord;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            // Administrador General - Marisol Ramos (Person 1)
            [
                'person_id' => 1,
                'employee_number' => 'DEC-001',
                'employee_type_id' => 1,
                'position_id' => 1,
                'department_id' => 1,
                'supervisor_id' => null,
                'manager_id' => null,
                'shift_id' => 1,
                'hire_date' => '2018-01-15',
                'platform_registered_at' => now(),
                'base_salary' => 45000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => true,
            ],
            // Gerente - Francisco Vega (Person 2)
            [
                'person_id' => 2,
                'employee_number' => 'DEC-002',
                'employee_type_id' => 1,
                'position_id' => 2,
                'department_id' => 2,
                'supervisor_id' => 1,
                'manager_id' => 1,
                'shift_id' => 1,
                'hire_date' => '2019-03-01',
                'platform_registered_at' => now(),
                'base_salary' => 35000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => true,
            ],
            // Supervisora Cajas - Ana López (Person 3)
            [
                'person_id' => 3,
                'employee_number' => 'DEC-003',
                'employee_type_id' => 1,
                'position_id' => 3,
                'department_id' => 3,
                'supervisor_id' => 2,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2020-06-15',
                'platform_registered_at' => now(),
                'base_salary' => 18000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => true,
            ],
            // Supervisor Producción - Luis Martínez (Person 4)
            [
                'person_id' => 4,
                'employee_number' => 'DEC-004',
                'employee_type_id' => 1,
                'position_id' => 3,
                'department_id' => 4,
                'supervisor_id' => 2,
                'manager_id' => 2,
                'shift_id' => 2,
                'hire_date' => '2020-08-01',
                'platform_registered_at' => now(),
                'base_salary' => 18000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => true,
            ],
            // Supervisora Atención - Claudia Hernández (Person 5)
            [
                'person_id' => 5,
                'employee_number' => 'DEC-005',
                'employee_type_id' => 1,
                'position_id' => 3,
                'department_id' => 5,
                'supervisor_id' => 2,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2021-01-10',
                'platform_registered_at' => now(),
                'base_salary' => 18000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => true,
            ],
            // Empleado 1 - Juan Pérez (Person 6) - Chocolates
            [
                'person_id' => 6,
                'employee_number' => 'DEC-006',
                'employee_type_id' => 1,
                'position_id' => 4,
                'department_id' => 5,
                'supervisor_id' => 5,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2023-02-01',
                'platform_registered_at' => now(),
                'base_salary' => 8500.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'tuesday',
                'is_active' => true,
            ],
            // Empleado 2 - María González (Person 7) - Harinas
            [
                'person_id' => 7,
                'employee_number' => 'DEC-007',
                'employee_type_id' => 1,
                'position_id' => 4,
                'department_id' => 5,
                'supervisor_id' => 5,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2022-01-15',
                'platform_registered_at' => now(),
                'base_salary' => 9500.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'monday',
                'is_active' => true,
            ],
            // Empleado 3 - Pedro Ramírez (Person 8) - Almacén - SUSPENDIDO
            [
                'person_id' => 8,
                'employee_number' => 'DEC-008',
                'employee_type_id' => 1,
                'position_id' => 6,
                'department_id' => 4,
                'supervisor_id' => 4,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2023-08-01',
                'platform_registered_at' => now(),
                'base_salary' => 8000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'sunday',
                'is_active' => false,
            ],
            // Empleado 4 - Sofía Torres (Person 9) - Cajas
            [
                'person_id' => 9,
                'employee_number' => 'DEC-009',
                'employee_type_id' => 1,
                'position_id' => 5,
                'department_id' => 3,
                'supervisor_id' => 3,
                'manager_id' => 2,
                'shift_id' => 1,
                'hire_date' => '2020-03-10',
                'platform_registered_at' => now(),
                'base_salary' => 12000.00,
                'salary_type' => 'monthly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']),
                'rest_day' => 'wednesday',
                'is_active' => true,
            ],
            // Empleado 5 - Diego Morales (Person 10) - Por Hora
            [
                'person_id' => 10,
                'employee_number' => 'DEC-010',
                'employee_type_id' => 2,
                'position_id' => 8,
                'department_id' => 5,
                'supervisor_id' => 5,
                'manager_id' => 2,
                'shift_id' => 4,
                'hire_date' => '2024-01-15',
                'platform_registered_at' => now(),
                'base_salary' => 75.00,
                'salary_type' => 'hourly',
                'work_schedule' => json_encode(['monday', 'tuesday', 'wednesday', 'thursday', 'friday']),
                'rest_day' => 'saturday',
                'is_active' => true,
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }

        // Crear registros de antigüedad histórica
        $seniorityRecords = [
            // Juan Pérez - 3,840 horas = 1 año, 3 meses
            [
                'employee_id' => 6,
                'total_historical_hours' => 3840,
                'hours_per_workday_config' => 8,
                'workdays_per_week_config' => 6,
                'weeks_per_month_config' => 4.33,
                'months_per_year_config' => 12,
                'calculation_method' => 'hours',
                'real_hire_date' => '2023-02-01',
                'platform_registered_at' => now(),
                'impacts_vacations' => true,
                'impacts_christmas_bonus' => true,
                'impacts_profit_sharing' => true,
                'impacts_severance' => true,
                'impacts_recommendation_letter' => true,
                'status' => 'validated',
                'notes' => 'Antigüedad capturada manualmente desde sistema anterior.',
                'created_by' => 1,
                'validated_by' => 1,
                'validated_at' => now(),
            ],
            // María González - 7,680 horas = 2 años, 6 meses
            [
                'employee_id' => 7,
                'total_historical_hours' => 7680,
                'hours_per_workday_config' => 8,
                'workdays_per_week_config' => 6,
                'weeks_per_month_config' => 4.33,
                'months_per_year_config' => 12,
                'calculation_method' => 'hours',
                'real_hire_date' => '2022-01-15',
                'platform_registered_at' => now(),
                'impacts_vacations' => true,
                'impacts_christmas_bonus' => true,
                'impacts_profit_sharing' => true,
                'impacts_severance' => true,
                'impacts_recommendation_letter' => true,
                'status' => 'validated',
                'notes' => 'Antigüedad capturada manualmente desde sistema anterior.',
                'created_by' => 1,
                'validated_by' => 1,
                'validated_at' => now(),
            ],
            // Pedro Ramírez - 2,100 horas = 8 meses, 180 horas
            [
                'employee_id' => 8,
                'total_historical_hours' => 2100,
                'hours_per_workday_config' => 8,
                'workdays_per_week_config' => 6,
                'weeks_per_month_config' => 4.33,
                'months_per_year_config' => 12,
                'calculation_method' => 'hours',
                'real_hire_date' => '2023-08-01',
                'platform_registered_at' => now(),
                'impacts_vacations' => true,
                'impacts_christmas_bonus' => true,
                'impacts_profit_sharing' => true,
                'impacts_severance' => true,
                'impacts_recommendation_letter' => true,
                'status' => 'validated',
                'notes' => 'Antigüedad capturada manualmente desde sistema anterior.',
                'created_by' => 1,
                'validated_by' => 1,
                'validated_at' => now(),
            ],
            // Sofía Torres - 14,400 horas = 4 años, 8 meses
            [
                'employee_id' => 9,
                'total_historical_hours' => 14400,
                'hours_per_workday_config' => 8,
                'workdays_per_week_config' => 6,
                'weeks_per_month_config' => 4.33,
                'months_per_year_config' => 12,
                'calculation_method' => 'hours',
                'real_hire_date' => '2020-03-10',
                'platform_registered_at' => now(),
                'impacts_vacations' => true,
                'impacts_christmas_bonus' => true,
                'impacts_profit_sharing' => true,
                'impacts_severance' => true,
                'impacts_recommendation_letter' => true,
                'status' => 'validated',
                'notes' => 'Antigüedad capturada manualmente desde sistema anterior.',
                'created_by' => 1,
                'validated_by' => 1,
                'validated_at' => now(),
            ],
            // Diego Morales - 620 horas
            [
                'employee_id' => 10,
                'total_historical_hours' => 620,
                'hours_per_workday_config' => 6,
                'workdays_per_week_config' => 5,
                'weeks_per_month_config' => 4.33,
                'months_per_year_config' => 12,
                'calculation_method' => 'hours',
                'real_hire_date' => '2024-01-15',
                'platform_registered_at' => now(),
                'impacts_vacations' => false,
                'impacts_christmas_bonus' => false,
                'impacts_profit_sharing' => false,
                'impacts_severance' => true,
                'impacts_recommendation_letter' => true,
                'status' => 'validated',
                'notes' => 'Empleado por hora. Antigüedad en horas reconocidas.',
                'created_by' => 1,
                'validated_by' => 1,
                'validated_at' => now(),
            ],
        ];

        foreach ($seniorityRecords as $record) {
            $seniority = EmployeeSeniorityHourRecord::create($record);
            $seniority->calculateSeniority();
            $seniority->save();
        }
    }
}
