<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Person;

class PersonSeeder extends Seeder
{
    public function run(): void
    {
        $people = [
            // Administrador General - Marisol Ramos
            [
                'first_name' => 'Marisol',
                'last_name' => 'Ramos',
                'middle_name' => 'Elena',
                'email' => 'admin@decorarte.demo',
                'phone' => '555-100-0001',
                'mobile' => '555-200-0001',
                'date_of_birth' => '1985-03-15',
                'gender' => 'female',
                'curp' => 'RAME850315MDFMSL01',
                'rfc' => 'RAME850315ABC',
                'nss' => '12345678901',
                'address' => 'Av. Insurgentes 100, Col. Roma',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06700',
                'emergency_contact_name' => 'Carlos Ramos',
                'emergency_contact_phone' => '555-300-0001',
                'emergency_contact_relation' => 'Esposo',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Gerente - Francisco Vega
            [
                'first_name' => 'Francisco',
                'last_name' => 'Vega',
                'middle_name' => 'Antonio',
                'email' => 'gerente@decorarte.demo',
                'phone' => '555-100-0002',
                'mobile' => '555-200-0002',
                'date_of_birth' => '1980-07-22',
                'gender' => 'male',
                'curp' => 'VEAF800722HDFGRC02',
                'rfc' => 'VEAF800722DEF',
                'nss' => '12345678902',
                'address' => 'Calle Reforma 200, Col. Juárez',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06600',
                'emergency_contact_name' => 'Laura Vega',
                'emergency_contact_phone' => '555-300-0002',
                'emergency_contact_relation' => 'Esposa',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Supervisora Cajas - Ana López
            [
                'first_name' => 'Ana',
                'last_name' => 'López',
                'middle_name' => 'María',
                'email' => 'ana.supervisor@decorarte.demo',
                'phone' => '555-100-0003',
                'mobile' => '555-200-0003',
                'date_of_birth' => '1990-11-08',
                'gender' => 'female',
                'curp' => 'LOMA901108MDFPNR03',
                'rfc' => 'LOMA901108GHI',
                'nss' => '12345678903',
                'address' => 'Av. Universidad 300, Col. Del Valle',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '03100',
                'emergency_contact_name' => 'Pedro López',
                'emergency_contact_phone' => '555-300-0003',
                'emergency_contact_relation' => 'Padre',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Supervisor Producción - Luis Martínez
            [
                'first_name' => 'Luis',
                'last_name' => 'Martínez',
                'middle_name' => 'Fernando',
                'email' => 'luis.supervisor@decorarte.demo',
                'phone' => '555-100-0004',
                'mobile' => '555-200-0004',
                'date_of_birth' => '1988-05-20',
                'gender' => 'male',
                'curp' => 'MALF880520HDFRNS04',
                'rfc' => 'MALF880520JKL',
                'nss' => '12345678904',
                'address' => 'Calle Hidalgo 400, Col. Centro',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06000',
                'emergency_contact_name' => 'Rosa Martínez',
                'emergency_contact_phone' => '555-300-0004',
                'emergency_contact_relation' => 'Madre',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Supervisora Atención - Claudia Hernández
            [
                'first_name' => 'Claudia',
                'last_name' => 'Hernández',
                'middle_name' => 'Isabel',
                'email' => 'claudia.supervisor@decorarte.demo',
                'phone' => '555-100-0005',
                'mobile' => '555-200-0005',
                'date_of_birth' => '1992-09-12',
                'gender' => 'female',
                'curp' => 'HEIC920912MDFRND05',
                'rfc' => 'HEIC920912MNO',
                'nss' => '12345678905',
                'address' => 'Av. Patriotismo 500, Col. San Pedro',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '03800',
                'emergency_contact_name' => 'Jorge Hernández',
                'emergency_contact_phone' => '555-300-0005',
                'emergency_contact_relation' => 'Hermano',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Empleado 1 - Juan Pérez (Chocolates)
            [
                'first_name' => 'Juan',
                'last_name' => 'Pérez',
                'middle_name' => 'Carlos',
                'email' => 'juan.perez@decorarte.demo',
                'phone' => '555-100-0006',
                'mobile' => '555-200-0006',
                'date_of_birth' => '1995-01-25',
                'gender' => 'male',
                'curp' => 'PECJ950125HDFRNN06',
                'rfc' => 'PECJ950125PQR',
                'nss' => '12345678906',
                'address' => 'Calle Morelos 600, Col. Doctores',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06720',
                'emergency_contact_name' => 'María Pérez',
                'emergency_contact_phone' => '555-300-0006',
                'emergency_contact_relation' => 'Madre',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Empleado 2 - María González (Harinas)
            [
                'first_name' => 'María',
                'last_name' => 'González',
                'middle_name' => 'Elena',
                'email' => 'maria.gonzalez@decorarte.demo',
                'phone' => '555-100-0007',
                'mobile' => '555-200-0007',
                'date_of_birth' => '1993-04-18',
                'gender' => 'female',
                'curp' => 'GOEM930418MDFNRL07',
                'rfc' => 'GOEM930418STU',
                'nss' => '12345678907',
                'address' => 'Av. Cuauhtémoc 700, Col. Narvarte',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '03020',
                'emergency_contact_name' => 'Roberto González',
                'emergency_contact_phone' => '555-300-0007',
                'emergency_contact_relation' => 'Padre',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Empleado 3 - Pedro Ramírez (Almacén) - SUSPENDIDO
            [
                'first_name' => 'Pedro',
                'last_name' => 'Ramírez',
                'middle_name' => 'Antonio',
                'email' => 'pedro.ramirez@decorarte.demo',
                'phone' => '555-100-0008',
                'mobile' => '555-200-0008',
                'date_of_birth' => '1996-08-30',
                'gender' => 'male',
                'curp' => 'RAPA960830HDFMND08',
                'rfc' => 'RAPA960830VWX',
                'nss' => '12345678908',
                'address' => 'Calle Zaragoza 800, Col. Portales',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '03300',
                'emergency_contact_name' => 'Carmen Ramírez',
                'emergency_contact_phone' => '555-300-0008',
                'emergency_contact_relation' => 'Esposa',
                'status' => Person::STATUS_ACCOUNT_SUSPENDED,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Empleado 4 - Sofía Torres (Cajas)
            [
                'first_name' => 'Sofía',
                'last_name' => 'Torres',
                'middle_name' => 'Isabel',
                'email' => 'sofia.torres@decorarte.demo',
                'phone' => '555-100-0009',
                'mobile' => '555-200-0009',
                'date_of_birth' => '1989-12-05',
                'gender' => 'female',
                'curp' => 'TOIS891205MDFRNF09',
                'rfc' => 'TOIS891205YZA',
                'nss' => '12345678909',
                'address' => 'Av. Revolución 900, Col. San Ángel',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '01000',
                'emergency_contact_name' => 'Daniel Torres',
                'emergency_contact_phone' => '555-300-0009',
                'emergency_contact_relation' => 'Esposo',
                'status' => Person::STATUS_EMPLOYEE_ACTIVE,
                'type' => Person::TYPE_EMPLOYEE,
            ],
            // Empleado 5 - Diego Morales (Por Hora)
            [
                'first_name' => 'Diego',
                'last_name' => 'Morales',
                'middle_name' => 'Fernando',
                'email' => 'diego.morales@decorarte.demo',
                'phone' => '555-100-0010',
                'mobile' => '555-200-0010',
                'date_of_birth' => '1998-02-14',
                'gender' => 'male',
                'curp' => 'MODF980214HDFRRL10',
                'rfc' => 'MODF980214BCD',
                'nss' => '12345678910',
                'address' => 'Calle Madero 1000, Col. Centro',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06000',
                'emergency_contact_name' => 'Lucía Morales',
                'emergency_contact_phone' => '555-300-0010',
                'emergency_contact_relation' => 'Madre',
                'status' => Person::STATUS_EMPLOYEE_HOURLY,
                'type' => Person::TYPE_EMPLOYEE_HOURLY,
            ],
            // Candidato 1 - Laura Sánchez
            [
                'first_name' => 'Laura',
                'last_name' => 'Sánchez',
                'middle_name' => 'María',
                'email' => 'laura.sanchez@email.com',
                'phone' => '555-100-0011',
                'mobile' => '555-200-0011',
                'date_of_birth' => '1997-06-20',
                'gender' => 'female',
                'curp' => 'SAML970620MDFNRL11',
                'rfc' => 'SAML970620EFG',
                'nss' => null,
                'address' => 'Av. Tlalpan 1100, Col. Pedregal',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '04500',
                'emergency_contact_name' => 'Miguel Sánchez',
                'emergency_contact_phone' => '555-300-0011',
                'emergency_contact_relation' => 'Padre',
                'status' => Person::STATUS_PROSPECT_INTERVIEW,
                'type' => Person::TYPE_CANDIDATE,
            ],
            // Candidato 2 - Roberto Medina
            [
                'first_name' => 'Roberto',
                'last_name' => 'Medina',
                'middle_name' => 'Carlos',
                'email' => 'roberto.medina@email.com',
                'phone' => '555-100-0012',
                'mobile' => '555-200-0012',
                'date_of_birth' => '1994-10-10',
                'gender' => 'male',
                'curp' => 'MECR941010HDFDNL12',
                'rfc' => 'MECR941010HIJ',
                'nss' => null,
                'address' => 'Calle Oaxaca 1200, Col. Roma',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06700',
                'emergency_contact_name' => 'Ana Medina',
                'emergency_contact_phone' => '555-300-0012',
                'emergency_contact_relation' => 'Madre',
                'status' => Person::STATUS_CANDIDATE_EVAL_PENDING,
                'type' => Person::TYPE_CANDIDATE,
            ],
            // Candidato 3 - Natalia Pérez
            [
                'first_name' => 'Natalia',
                'last_name' => 'Pérez',
                'middle_name' => 'Isabel',
                'email' => 'natalia.perez@email.com',
                'phone' => '555-100-0013',
                'mobile' => '555-200-0013',
                'date_of_birth' => '1999-03-08',
                'gender' => 'female',
                'curp' => 'PEIN990308MDFRNT13',
                'rfc' => 'PEIN990308KLM',
                'nss' => null,
                'address' => 'Av. Insurgentes Sur 1300, Col. Chimalistac',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '01070',
                'emergency_contact_name' => 'Fernando Pérez',
                'emergency_contact_phone' => '555-300-0013',
                'emergency_contact_relation' => 'Padre',
                'status' => Person::STATUS_TRIAL_STORE,
                'type' => Person::TYPE_CANDIDATE,
            ],
            // Exempleado - Carlos Herrera
            [
                'first_name' => 'Carlos',
                'last_name' => 'Herrera',
                'middle_name' => 'Antonio',
                'email' => 'carlos.herrera@email.com',
                'phone' => '555-100-0014',
                'mobile' => '555-200-0014',
                'date_of_birth' => '1987-07-15',
                'gender' => 'male',
                'curp' => 'HECA870715HDFRRN14',
                'rfc' => 'HECA870715NOP',
                'nss' => '12345678914',
                'address' => 'Calle Veracruz 1400, Col. Condesa',
                'city' => 'Ciudad de México',
                'state' => 'CDMX',
                'zip_code' => '06140',
                'emergency_contact_name' => 'Diana Herrera',
                'emergency_contact_phone' => '555-300-0014',
                'emergency_contact_relation' => 'Esposa',
                'status' => Person::STATUS_EX_EMPLOYEE_RECOMMENDED,
                'type' => Person::TYPE_EX_EMPLOYEE,
            ],
        ];

        foreach ($people as $person) {
            Person::create($person);
        }
    }
}
